title : хви
author :
  name : morlay
  email : morlay.null@gmail.com
  github : morlay
  weibo : username


permalink: /:categories/:year/:month/:day/:title

paginate: 5

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: rdiscount
pygments: true

production_url : http://morlay.github.io

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

atom_path : /atom.xml
rss_path : /rss.xml